export let translate = {};
export const setLanguage = (x) => {
    switch (x) {
        case 'en':
            translate = {
                lang: 'en',
                buttonCloseExercise: 'Your state will be automatically saved',
                infoCongratulation: 'Congratultaion!',
                buttonInfoCongratulation: 'Back to exercises menu',
                buttonInfoCongratulationRestart: 'Start this exercise all over again',
                buttonIKnow: 'I knew',
                buttonIDontKnow: "I don't knew",
                buttonSimpleLotter: 'Simple Lottery',
                buttonCheckOut: 'Check out',
                buttonCheckOutToNext: 'Next',
                textSummary: 'Summary',
                buttonEnableAutoVoice: 'Enable automatically voice',
                buttonDisableRotate: 'Disable rotate',
                buttonRestartProgress: 'Restart progress',
                buttonCloseApplication: 'Close application',
                yourPlatform: 'Your platform',
                polish: 'Polish',
                english: 'English',
                pl: 'Pl',
                en: 'En',
                abouts: 'Autor: semDesign<br />Contact: aleksander.nyczyk@gmail.com<br />Version: ',
                gt: 'Google Translate',
                privacy: 'Privacy',
                fullItemsList: 'Full items list',
                flashcards: 'Flashcards',
                lottery: 'Lottery',
                noResultSearch: 'no result, change the direction of translation: ',
                searchOnThisPage: 'Search on this page',
                changeDirectionLanguage: 'you can change the direction of translation: ',
                found: 'found',
                or: 'or',
                summary: 'Summary',
                sentenceYouDidntKnow: 'You didn\'t know (at least once)',
                sentenceNotAnswered: 'You have not answered yet',
                sentenceYouKnew: 'You knew (or you learned)',
                toRepeat: 'To repeat',
                toggleToRepeatShow: 'The whole list to repeat',
                toggleToRepeatHide: 'Lottery',
                TryToWriteATranslate: 'Try to write a translate',
                infoDescription: 'Remember, English words often have many meanings that can also depend on the context. We chose the most popular words and sometimes less popular alternatives in brackets. If you need more complete translation, you can use the icon with the Google Translate. The icon is at the bottom-right corner of the flashcard. If you have any questions or suggestions, please send an',
                additionally: 'Additionally',
                showAnswer: 'Show the correct answer for a moment',
                listenTranslate: 'Listen to the translation'

            };
            break;
        default: //pl
            translate = {
                lang: 'pl',
                buttonCloseExercise: 'Twój stan zostanie automatycznie zapisany',
                infoCongratulation: 'Gratulacje!',
                buttonInfoCongratulation: 'Wróć do menu ćwiczeń',
                buttonInfoCongratulationRestart: 'Zacznij to ćwiczenie od nowa',
                buttonIKnow: 'Wiedziałem/am',
                buttonIDontKnow: "Nie wiedziałem/am",
                buttonSimpleLotter: 'Zwykłe losowanie',
                buttonCheckOut: 'Sprawdź',
                buttonCheckOutToNext: 'Następny',
                textSummary: 'Podsumowanie',
                buttonEnableAutoVoice: 'Włączaj automatycznie głos',
                buttonDisableRotate: 'Wyłącz obracanie',
                buttonRestartProgress: 'Restartuj postęp',
                buttonCloseApplication: 'Zamknij aplikacje',
                yourPlatform: 'Twoja platforma',
                polish: 'Polski',
                english: 'Angielski',
                pl: 'Pl',
                en: 'En',
                abouts: 'Autor: semDesign<br />Kontakt: aleksander.nyczyk@gmail.com<br />Wersja: ',
                gt: 'Google Translator',
                privacy: 'Prywatność',
                fullItemsList: 'Pełna lista',
                flashcards: 'Fiszki',
                lottery: 'Losowanie',
                noResultSearch: 'bez rezulatatu, zmień kierunek: ',
                searchOnThisPage: 'Szukaj na tej stronie',
                changeDirectionLanguage: 'możesz zmienić kierunek tłumaczenia: ',
                found: 'znaleziono',
                or: 'albo',
                summary: 'Podsumowanie',
                sentenceYouDidntKnow: 'Nie wiedziałeś (przynajmniej raz)',
                sentenceNotAnswered: 'Jeszcze nie odpowiadałeś',
                sentenceYouKnew: 'Wiedziałeś (lub się nauczyłeś)',
                toRepeat: 'Do powtórki',
                toggleToRepeatShow: 'Cała lista do powtórki',
                toggleToRepeatHide: 'Loteria',
                TryToWriteATranslate: 'Spróbuj napisać tłumaczenie',
                infoDescription: 'Pamiętaj, że angielskie słowa mają często wiele znaczeń, także zależnych od kontekstu. Do aplikacji starano się wybrać najczęściej stosowane tłumaczenia oraz ewentualne alternatywy w nawiasach. Jeśli potrzebujesz kompletniejszego tłumaczenia, możesz użyć ikony z Transaltora Google, która znajduje się w prawym dolnym rogu fiszki. Wszelkie pytania i sugestie proszę kierować na ',
                additionally: 'Dodatkowo',
                showAnswer: 'Pokaż na chwilę poprawną odpowieź',
                listenTranslate: 'Wysłuchaj tłumaczenia'
            };
    }
};